# Generated by Django 2.2 on 2020-10-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NR', 'No registrado'), ('R', 'Registrado'), ('ET', 'En trámite'), ('EV', 'Esperando vuelo')], default='No registrado', max_length=2)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterTraveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NR', 'No registrado'), ('R', 'Registrado'), ('ET', 'En trámite'), ('EV', 'Esperando vuelo')], default='No registrado', max_length=2)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opciones', models.CharField(choices=[('E', 'Estudio'), ('C', 'Cultural'), ('T', 'Trabajo')], default='-', max_length=20)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RegisterTraveller')),
            ],
        ),
    ]
