# Generated by Django 2.2 on 2020-10-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='register',
            new_name='regist',
        ),
    ]
