# Generated by Django 2.2 on 2020-12-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='email',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
    ]
