# Generated by Django 2.2 on 2020-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitud_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registertraveller',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
    ]
