# Generated by Django 2.2 on 2020-12-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitud_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='actividad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='info',
            field=models.CharField(default='', max_length=50),
        ),
    ]
