# Generated by Django 2.2 on 2020-10-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201015_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registertraveller',
            old_name='password',
            new_name='password1',
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estad', models.CharField(choices=[('NA', 'No Aprobado'), ('A', 'Aprobado')], default='-', max_length=20)),
                ('reg_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RegisterHost')),
                ('regist1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RegisterTraveller')),
            ],
        ),
    ]
