# Generated by Django 2.2 on 2020-12-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201209_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='edad',
        ),
    ]
