# Generated by Django 2.2 on 2020-12-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201209_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='actividad',
        ),
        migrations.AddField(
            model_name='destiny',
            name='actividad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
