# Generated by Django 2.2 on 2020-12-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_solicitud_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='viajante',
        ),
    ]
