# Generated by Django 2.2 on 2020-12-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201210_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destiny',
            name='actividad',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(default='', max_length=50)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Destiny')),
            ],
        ),
    ]
