# Generated by Django 2.2 on 2020-12-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201209_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado_soli',
            field=models.CharField(choices=[('NA', 'No Aprobado'), ('A', 'Aprobado')], default='NA', max_length=50),
        ),
    ]
