# Generated by Django 2.2 on 2020-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201015_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='opciones',
            field=models.CharField(choices=[('E', 'Estudio'), ('C', 'Cultural'), ('T', 'Trabajo')], default='R', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estad',
            field=models.CharField(choices=[('NA', 'No Aprobado'), ('A', 'Aprobado')], default='-', max_length=20),
        ),
    ]
