# Generated by Django 2.2 on 2020-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201015_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerhost',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programa',
            name='opciones',
            field=models.CharField(choices=[('E', 'Estudio'), ('C', 'Cultural'), ('T', 'Trabajo')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='registertraveller',
            name='status',
            field=models.CharField(choices=[('NR', 'No registrado'), ('R', 'Registrado'), ('ET', 'En trámite'), ('EV', 'Esperando vuelo')], default='R', max_length=2),
        ),
    ]
