# Generated by Django 2.2 on 2020-12-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitud_estado_soli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='estado_soli',
            new_name='estado',
        ),
    ]
