# Generated by Django 2.2 on 2020-12-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201210_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='actividad',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Destiny'),
        ),
    ]
