# Generated by Django 2.2 on 2020-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201015_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhost',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
