# Generated by Django 2.2 on 2020-10-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201015_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerhost',
            old_name='capacidad',
            new_name='disponibilidad',
        ),
        migrations.AlterField(
            model_name='registerhost',
            name='status',
            field=models.CharField(choices=[('NR', 'No registrado'), ('R', 'Registrado'), ('ET', 'En trámite'), ('EV', 'Esperando vuelo')], default='R', max_length=2),
        ),
    ]
