# Generated by Django 2.2 on 2020-12-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201210_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='dest',
        ),
        migrations.AddField(
            model_name='actividad',
            name='activit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.RegisterTraveller'),
        ),
    ]
