# Generated by Django 2.2 on 2020-12-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201209_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertraveller',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
