# Generated by Django 2.2 on 2020-12-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201210_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='activit',
        ),
    ]
